"""Generate small model modules or deterministic compressed catalogs."""

import ast
import gzip
import json
import zlib
from collections.abc import Iterable, Mapping
from pathlib import Path
from pprint import pformat

from tokenary._model_names import make_enum_names
from tokenary._serialization import canonical_json, content_hash, write_atomic
from tokenary.catalog import CATALOG_FORMAT_VERSION, PricingCatalog
from tokenary.pricing import ModelPricing


def build_catalog_payload(
    raw_prices: Mapping[str, object],
    *,
    models: Iterable[str] | None = None,
    source: str = "custom",
    previous_names: Mapping[str, str] | None = None,
) -> dict[str, object]:
    available = {
        name: data
        for name, data in raw_prices.items()
        if name != "sample_spec" and isinstance(data, dict)
    }
    selected = set(available) if models is None else set(models)
    missing = selected - available.keys()
    if missing:
        raise ValueError(f"Unknown models: {', '.join(sorted(missing))}")
    if not selected:
        raise ValueError("Select at least one model")

    # Resolve against the entire source before filtering so subset names agree.
    all_names = make_enum_names(available, previous_names)
    names = {name: all_names[name] for name in sorted(selected)}
    prices = {}
    for name in sorted(selected):
        data = {
            key: value
            for key, value in available[name].items()
            if key in {"litellm_provider", "mode"} or "cost" in key
        }
        # Keep unknown upstream price fields, but validate the shared known fields.
        ModelPricing.model_validate(data)
        prices[name] = data

    return {
        "format_version": CATALOG_FORMAT_VERSION,
        "metadata": {
            "source": source,
            "source_sha256": content_hash(raw_prices),
            "catalog_sha256": content_hash({"models": prices, "enum_names": names}),
        },
        "enum_names": names,
        "models": prices,
    }


def _render_payload_as_python(payload: dict[str, object]) -> str:
    lines = [
        "# Auto-generated by tokenary-generate. Do not edit manually.",
        "# Source and content checksums are stored in CATALOG.metadata.",
        "",
        "from enum import StrEnum",
        "from functools import partial",
        "",
        "from tokenary import PricingCatalog",
        "from tokenary import calculate as _calculate",
        "",
        "",
        "class ModelName(StrEnum):",
    ]
    for model, alias in payload["enum_names"].items():
        assignment = f"    {alias} = {model!r}"
        if len(assignment) <= 88:
            lines.append(assignment)
        else:
            lines.extend([f"    {alias} = (", f"        {model!r}", "    )"])
    rendered_payload = pformat(payload, sort_dicts=True, width=84)
    lines.extend(
        [
            "",
            "",
            "CATALOG = PricingCatalog.from_dict(",
            *[f"    {line}" for line in rendered_payload.splitlines()],
            ")",
            "",
            "calculate = partial(_calculate, catalog=CATALOG)",
        ]
    )
    return "\n".join(lines) + "\n"


def render_python_catalog(
    raw_prices: Mapping[str, object],
    *,
    models: Iterable[str] | None = None,
    source: str = "custom",
    previous_names: Mapping[str, str] | None = None,
) -> str:
    return _render_payload_as_python(
        build_catalog_payload(
            raw_prices, models=models, source=source, previous_names=previous_names
        )
    )


def render_catalog_file(payload: dict[str, object], output_path: str | Path) -> bytes:
    path = Path(output_path)
    if path.suffix == ".py":
        return _render_payload_as_python(payload).encode("utf-8")
    if path.suffix == ".gz":
        return gzip.compress(canonical_json(payload), mtime=0)
    if path.suffix == ".json":
        return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")
    raise ValueError("Output must end in .py, .json, or .json.gz")


def catalog_file_matches(path: Path, rendered: bytes) -> bool:
    if not path.exists():
        return False
    existing = path.read_bytes()
    if path.suffix in {".json", ".gz"}:
        try:
            # Ignore formatting, line endings and compressor implementation.
            if path.suffix == ".gz":
                existing = gzip.decompress(existing)
                rendered = gzip.decompress(rendered)
            return canonical_json(json.loads(existing)) == canonical_json(
                json.loads(rendered)
            )
        except (OSError, EOFError, ValueError, zlib.error):
            return False
    if path.suffix != ".py":
        return existing == rendered
    try:
        # Formatting tools must not introduce semantic drift into --check.
        return ast.dump(ast.parse(existing)) == ast.dump(ast.parse(rendered))
    except SyntaxError:
        return False


def read_existing_enum_names(output_path: str | Path) -> dict[str, str]:
    path = Path(output_path)
    if not path.exists():
        return {}
    if path.suffix != ".py":
        return PricingCatalog.from_file(path).enum_names
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "ModelName":
            for member in node.body:
                if (
                    isinstance(member, ast.Assign)
                    and len(member.targets) == 1
                    and isinstance(member.targets[0], ast.Name)
                ):
                    model = ast.literal_eval(member.value)
                    if isinstance(model, str):
                        names[model] = member.targets[0].id
    return names


def write_python_catalog_file(
    raw_prices: Mapping[str, object],
    output_path: str | Path,
    *,
    models: Iterable[str] | None = None,
    source: str = "custom",
    previous_names: Mapping[str, str] | None = None,
) -> Path:
    previous = dict(previous_names or {})
    previous.update(read_existing_enum_names(output_path))
    rendered = render_python_catalog(
        raw_prices, models=models, source=source, previous_names=previous
    )
    return write_atomic(output_path, rendered.encode("utf-8"))
